'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HslScada.Controls_Net45.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AnalogSliderSlot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AnalogSliderSlot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AnnunciatorOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AnnunciatorOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AnnunciatorOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AnnunciatorOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BckgndBlack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BckgndBlack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BckgndGrayLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BckgndGrayLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BckgndGrayLightLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BckgndGrayLightLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BckgndTan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BckgndTan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BluePilotOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BluePilotOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BluePilotOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BluePilotOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlueSevenSegmentDot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueSevenSegmentDot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChromeKnob() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChromeKnob", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ClearBackgroundFrame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClearBackgroundFrame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConveyorOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConveyorOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConveyorOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConveyorOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DigitalPanelMeter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DigitalPanelMeter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DigitalPanelMeterLeftHalf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DigitalPanelMeterLeftHalf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DigitalPanelMeterR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DigitalPanelMeterR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Drum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Drum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DrumBlack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DrumBlack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DrumBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DrumBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DrumGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DrumGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DrumRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DrumRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Elbow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Elbow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EstopButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EstopButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EstopButtonDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EstopButtonDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FanBlades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FanBlades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FanCenterCap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FanCenterCap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FanFrame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FanFrame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaugeNeedle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaugeNeedle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaugeNeedleShadow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaugeNeedleShadow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaugeSilverNoNeedle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaugeSilverNoNeedle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenDecimal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenDecimal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenPilotOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenPilotOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenPilotOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenPilotOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HorizontalPipe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HorizontalPipe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HydraulicCylinder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HydraulicCylinder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HydraulicCylinderRod() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HydraulicCylinderRod", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JaggedBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JaggedBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ketlle1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ketlle1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ketlle1Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ketlle1Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ketlle1Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ketlle1Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KetlleLongLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KetlleLongLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KetlleLongLegsGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KetlleLongLegsGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KetlleLongLegsRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KetlleLongLegsRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KettleShortLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KettleShortLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KettleShortLegsGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KettleShortLegsGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KettleShortLegsRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KettleShortLegsRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KeypadBlack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KeypadBlack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KeyPadKey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KeyPadKey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KeyPadKeyDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KeyPadKeyDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KeypadKeyWide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KeypadKeyWide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KeypadKeyWideDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KeypadKeyWideDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7Segment_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7Segment_Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7Segment0Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7Segment0Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7Segment1Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7Segment1Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7Segment2Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7Segment2Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7Segment3Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7Segment3Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7Segment4Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7Segment4Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7Segment5Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7Segment5Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7Segment6Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7Segment6Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7Segment7Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7Segment7Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7Segment8Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7Segment8Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7Segment9Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7Segment9Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7SegmentDecimalRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7SegmentDecimalRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LED7SegmentOffRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED7SegmentOffRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LegendPlate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LegendPlate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LegendPlateLargeWithNut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LegendPlateLargeWithNut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LegendPlateShort() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LegendPlateShort", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LegendPlateSmallWithNut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LegendPlateSmallWithNut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Legs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Legs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LinearMeterBase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinearMeterBase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LinearMeterNeedle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinearMeterNeedle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LinearMeterVertical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinearMeterVertical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LinearMeterVerticalNeedle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LinearMeterVerticalNeedle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MAButtonGray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MAButtonGray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MAButtonGrayPressedRing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MAButtonGrayPressedRing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MeterBase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MeterBase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MeterNeedle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MeterNeedle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MeterNoNeedle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MeterNoNeedle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MeterNoNeedleCenterScale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MeterNoNeedleCenterScale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MeterRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MeterRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MeterScale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MeterScale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MeterScaleBackGround() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MeterScaleBackGround", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MotorGray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MotorGray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MotorGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MotorGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MotorRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MotorRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MotorYellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MotorYellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Needle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Needle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PilotLightDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PilotLightDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Plate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Plate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PneumaticBallValveOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PneumaticBallValveOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PneumaticBallValveOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PneumaticBallValveOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RedDecimal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedDecimal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RedPilotOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedPilotOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RedPilotOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedPilotOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RSCorPumpOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RSCorPumpOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RSCorPumpOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RSCorPumpOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SelectorSwitchCenterNoNut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectorSwitchCenterNoNut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SiloGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SiloGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SiloRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SiloRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SiloWithLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SiloWithLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SiloWithLegsGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SiloWithLegsGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SiloWithLegsRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SiloWithLegsRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SquareButtonBlueOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SquareButtonBlueOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SquareButtonBlueOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SquareButtonBlueOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SquareButtonDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SquareButtonDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SquareButtonGreenOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SquareButtonGreenOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SquareButtonGreenOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SquareButtonGreenOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SquareButtonRedOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SquareButtonRedOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SquareButtonRedOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SquareButtonRedOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StackLightBase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StackLightBase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StackLightCap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StackLightCap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StackLightElementGray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StackLightElementGray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tank1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tank1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tank1Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tank1Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tank1Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tank1Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tank1WithLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tank1WithLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tank1WithLegsGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tank1WithLegsGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tank1WithLegsRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tank1WithLegsRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TankWithWindow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TankWithWindow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tee1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tee1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TempController() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TempController", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TempControllerButton1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TempControllerButton1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TempControllerButton1Pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TempControllerButton1Pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TempControllerButton2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TempControllerButton2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TempControllerButton2Pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TempControllerButton2Pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TempControllerButton3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TempControllerButton3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TempControllerButton3Pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TempControllerButton3Pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TempControllerButton4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TempControllerButton4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TempControllerButton4Pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TempControllerButton4Pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thermometer2Bulb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thermometer2Bulb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thermometer2BulbBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thermometer2BulbBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thermometer2BulbGrn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thermometer2BulbGrn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thermometer2Column() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thermometer2Column", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thermometer2ColumnBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thermometer2ColumnBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thermometer2ColumnGrn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thermometer2ColumnGrn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thermometer2Static() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thermometer2Static", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThermometerStatic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThermometerStatic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThumbDialBase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThumbDialBase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThumbDialFrame1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThumbDialFrame1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThumbDialFrame2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThumbDialFrame2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThumbDialFrame3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThumbDialFrame3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VerticalSlider() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VerticalSlider", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vessel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vessel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VesselGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VesselGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VesselRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VesselRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VesselRedWithLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VesselRedWithLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VesselWithLegs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VesselWithLegs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VesselWithLegsGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VesselWithLegsGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhitePilotOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhitePilotOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhitePilotOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhitePilotOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowPilotOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowPilotOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowPilotOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowPilotOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
